version: '3.8'
services:
  movies:
    image: saiteja2644/paytmmovies:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3
  recharge:
    image: saiteja2644/paytmrecharge:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
 train:
    image: saiteja2644/paytmdth:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
  
