version: '3.8'
services:
  movies:
    image: upendrayadav1abc/paytmdth:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3
  recharge:
    image: upendrayadav1abc/paytmrecharge:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
  dth:
    image: upendrayadav1abc/paytmmovies:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
  train:
    image: upendrayadav1abc/paytmtrain:latest
    ports:
      - "94:80"
    deploy:
      replicas: 3
  
