version: '3.8'
services:
  movies:
    image: saiteja2644/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  recharge:
    image: saiteja2644/paytmrecharge:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
 train:
    image: saiteja2644/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  
