version: '3.9'
services:
  movies:
    image: saiteja2644/paytmmovies:latest
    ports:
      - "81:80"
  recharge:
    image: saiteja2644/paytmrecharge:latest
    ports:
      - "82:80"
 train:
    image: saiteja2644/paytmdth:latest
    ports:
      - "83:80"
  
